import {
  Bot,
  Brain,
  Briefcase,
  Building,
  Building2,
  CircleHelp,
  ClipboardCheck,
  Code,
  DollarSign,
  Flame,
  HeartHandshake,
  Laptop,
  Loader2,
  MapPin,
  MessageCircle,
  Microscope,
  Rocket,
  Shield,
  Shuffle,
  Smile,
  Sparkles,
  Sprout,
  TrendingUp,
  Trophy,
  User,
  Users,
  UsersRound,
  Wallet,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react'

export const quizIconMap: Record<string, LucideIcon> = {
  bot: Bot,
  brain: Brain,
  briefcase: Briefcase,
  building: Building,
  'building-2': Building2,
  'circle-help': CircleHelp,
  'clipboard-check': ClipboardCheck,
  code: Code,
  'dollar-sign': DollarSign,
  flame: Flame,
  'heart-handshake': HeartHandshake,
  laptop: Laptop,
  loader: Loader2,
  'message-circle': MessageCircle,
  microscope: Microscope,
  pin: MapPin,
  rocket: Rocket,
  shield: Shield,
  shuffle: Shuffle,
  smile: Smile,
  sparkles: Sparkles,
  sprout: Sprout,
  'trending-up': TrendingUp,
  trophy: Trophy,
  user: User,
  users: Users,
  'users-round': UsersRound,
  wallet: Wallet,
  wrench: Wrench,
  zap: Zap,
}
